<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="android.ninetynine.auth.C1259_LoginUnverUser" tests="1" time="64.791" ignored="0" failures="1" timestamp="09 Nov 2020 13:15:57 GMT" skipped="0" hostname="daniamrth" errors="0">
  <testcase name="C1259_Login_UnverUser" time="64.791" classname="android.ninetynine.auth.C1259_LoginUnverUser">
    <failure type="java.lang.AssertionError" message="Object not found step failed">
      <![CDATA[java.lang.AssertionError: Object not found step failed
	at org.testng.Assert.fail(Assert.java:94)
	at android.ninetynine.util.GeneralUtilities.verifyelemen(GeneralUtilities.java:49)
	at android.ninetynine.util.GeneralUtilities.click(GeneralUtilities.java:58)
	at android.ninetynine.pageobjects.Login.Click_ModalNotNow(Login.java:55)
	at android.ninetynine.auth.C1259_LoginUnverUser.C1259_Login_UnverUser(C1259_LoginUnverUser.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- C1259_Login_UnverUser -->
</testsuite> <!-- android.ninetynine.auth.C1259_LoginUnverUser -->
